export const parts = [
 {id:'pi',name:'Raspberry Pi 4B',tag:'COMPUTE',subtitle:'4 GB · 3.3 V GPIO',x:300,y:185,w:215,h:235,detail:'Runs camera capture, inference, and the pan/tilt controller. Power through a dedicated USB-C 5.1 V supply. GPIO carries logic signals only. Motor power never comes from a GPIO pin.',pins:'BCM17 → STEP · BCM27 → DIR · BCM22 → nENBL · BCM18 → servo PWM · physical pin 6 → common ground',status:'Proposed GPIO assignment'},
 {id:'driver',name:'DRV8825 carrier',tag:'AZIMUTH DRIVER',subtitle:'STEP / DIR · current limited',x:650,y:165,w:215,h:155,detail:'Chopper driver for a bipolar stepper. VMOT requires 8.2–45 V; 12 V is a candidate rail, not a confirmed motor setting. Use at least 47 µF bulk capacitance near VMOT. Set the current limit from the exact carrier sense resistors and motor rating. Tie nRESET and nSLEEP high to 3.3 V; pull nENBL high with 10 kΩ so the driver starts disabled. M0/M1/M2 low selects full steps.',pins:'GPIO17 STEP · GPIO27 DIR · GPIO22 nENBL · 3V3 → nRESET/nSLEEP · 12 V candidate → VMOT · GND common',status:'Verify carrier and current limit'},
 {id:'stepper',name:'FITO278 stepper',tag:'AZIMUTH AXIS',subtitle:'Bipolar coils A / B',x:960,y:165,w:190,h:155,detail:'The motor identifier comes from the supplied hardware list. Its phase current, coil pairs, step angle, and gear ratio are not yet verified. Identify coils by resistance with power off. Do not infer coil wiring from cable colours.',pins:'A1/A2 → coil A · B1/B2 → coil B · verify the exact motor datasheet',status:'Motor specification required'},
 {id:'servo',name:'MG90S servo',tag:'PITCH AXIS',subtitle:'PWM · external regulated rail',x:650,y:390,w:215,h:135,detail:'Power from an external regulated 4.8–5.0 V supply sized for stall current. Share ground with the Pi. Start at the neutral position and calibrate travel on the actual assembly. Add a suitable logic buffer if the actual servo does not reliably accept 3.3 V PWM.',pins:'GPIO18 → PWM signal · external +5 V → V+ · GND common',status:'Calibrate PWM and travel'},
 {id:'camera',name:'Arducam Mini',tag:'CAMERA',subtitle:'Exact interface unverified',x:25,y:195,w:200,h:150,detail:'“Mini / UNO Mega2560” suggests an SPI module, but the exact SKU must be checked. Do not connect it to the CSI socket by assumption. A verified SPI camera requires its vendor driver and a separately reviewed SPI/I²C pin map. Camera power and logic levels remain unassigned until confirmed.',pins:'Interface, supply, and connector: TBD from exact module label',status:'Connection pending SKU'},
 {id:'power',name:'Power distribution',tag:'EXTERNAL SUPPLIES',subtitle:'Separate rails · common reference',x:300,y:550,w:565,h:125,detail:'Dedicated Pi USB-C supply; separate regulated servo rail; separate current-limited motor rail. Join supply grounds at a deliberate common reference. Add a physical motor-power disconnect, fuse sized to the verified wiring/load, and strain relief. Do not join positive rails or backfeed Pi power.',pins:'Pi: 5.1 V USB-C · servo: 4.8–5.0 V · stepper: candidate 12 V via fuse/disconnect · shared GND',status:'Supply sizing pending measurements'}
];
export function schematic(){return `<svg viewBox="0 0 1180 740" role="img" aria-label="Proposed Raspberry Pi, DRV8825, stepper, servo, camera and external power wiring"><defs><pattern id="dots" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".75" fill="#273442"/></pattern></defs><rect width="1180" height="740" fill="url(#dots)"/>
 <g fill="none" stroke-width="2"><path class="wire signal" d="M515 230H650M515 260H650M515 290H650"/><path class="wire motor" d="M865 230H960M865 260H960"/><path class="wire signal" d="M515 370H565V440H650"/><path class="wire pending" d="M225 260H300"/><path class="wire power" d="M730 550V525M810 550H905V350H755V320M400 550V420"/><path class="wire ground" d="M330 420V705H1100V320M680 525V705M680 320V355H600V705"/></g>
 <g class="wire-label"><text x="548" y="219">STEP</text><text x="548" y="250">DIR</text><text x="548" y="282">ENABLE</text><text x="884" y="219">COIL A</text><text x="884" y="282">COIL B</text><text x="574" y="430">PWM</text><text x="238" y="246">TBD</text><text x="920" y="352">VMOT</text><text x="746" y="544">5 V</text><text x="880" y="698">COMMON GROUND</text></g>
 ${parts.map(p=>`<g class="component" data-part="${p.id}" tabindex="0" role="button" aria-label="Inspect ${p.name}"><rect x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}" rx="8"/><rect class="part-accent" x="${p.x}" y="${p.y}" width="3" height="${p.h}" rx="1"/><text class="part-tag" x="${p.x+20}" y="${p.y+29}">${p.tag}</text><text class="part-name" x="${p.x+20}" y="${p.y+62}">${p.name}</text><text class="part-sub" x="${p.x+20}" y="${p.y+86}">${p.subtitle}</text>${p.id==='pi'?`<g fill="#84919d">${Array.from({length:20},(_,i)=>`<circle cx="${p.x+25+(i%10)*17}" cy="${p.y+135+Math.floor(i/10)*18}" r="3"/>`).join('')}</g><text class="part-sub" x="${p.x+20}" y="${p.y+204}">40-PIN HEADER · BCM NUMBERING</text>`:''}</g>`).join('')}
 <text class="schematic-caption" x="25" y="45">KESTREL / ELECTRICAL ARCHITECTURE</text><text class="part-sub" x="25" y="72">REV A · PROPOSED CONNECTIONS · NOT A VERIFIED AS-BUILT DRAWING</text></svg>`;}
export const pinRows=[['11','17','Output','DRV8825 STEP','Step pulses; deterministic timing required'],['13','27','Output','DRV8825 DIR','Direction; verify mechanical sign'],['15','22','Output','DRV8825 nENBL','Active low; 10 kΩ pull-up to 3.3 V'],['12','18','PWM','MG90S signal','Calibrate pulse range before mounting'],['1','3V3','Logic supply','DRV8825 nRESET + nSLEEP','High enables driver logic; not VMOT'],['6','GND','Reference','Common ground','Pi, driver, servo and supply grounds'],['—','—','Motor power','DRV8825 VMOT','8.2–45 V driver range; motor current TBD'],['—','—','Servo power','MG90S V+','External regulated 4.8–5.0 V'],['TBD','TBD','Camera','Arducam Mini','Verify SKU, pinout and driver first']];
